x = int(input('Entre com um valor inteiro: '))
print('{}x1 : {}'.format(x, x*1))
print('{}x2 : {}'.format(x, x*2))
print('{}x3 : {}'.format(x, x*3))
print('{}x4 : {}'.format(x, x*4))
print('{}x5 : {}'.format(x, x*5))
print('{}x6 : {}'.format(x, x*6))
print('{}x7 : {}'.format(x, x*7))
print('{}x8 : {}'.format(x, x*8))
print('{}x9 : {}'.format(x, x*9))
print('{}x10 : {}'.format(x, x*10))